import type { Metadata } from "next";
import { bonaNova } from "@/fonts/fonts";
import "./globals.css";
import { cn } from "@/lib/utils";
import Header from "@/components/Header/header";
import ThemeProvider from "@/components/Providers/ThemeProvider/theme-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" suppressHydrationWarning>
      <body
        className={cn(
          `min-h-screen bg-background font-bonanova antialiased`,
          bonaNova.className
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
